// ITI/Angular/Lab2/lab/task2/ImageSlider/src/app/slider/slider.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-slider',
  templateUrl: './slider.component.html',
  styleUrls: ['./slider.component.css'],
})
export class SliderComponent {
  img = document.getElementById('img');
  stop = document.getElementById('sb');
  images = [
    'assets/Images/1.jpg',
    'assets/Images/2.jpg',
    'assets/Images/3.jpg',
    'assets/Images/4.jpg',
    'assets/Images/5.jpg',
    'assets/Images/6.jpg',
  ];
  i = 0;
  interval: any;
  src: String = 'assets/Images/1.jpg';

  prevImg() {
    if (this.i <= 0) this.i = this.images.length;
    this.i--;
    this.src = this.images[this.i];
  }

  nextImg() {
    if (this.i >= this.images.length - 1) this.i = -1;
    this.i++;
    this.src = this.images[this.i];
  }

  slideImg() {
    this.interval = setInterval(()=> {
      //always use the arrow function to avoid the problem of this binding
      if (this.i >= this.images.length - 1) this.i = -1;
      this.i++;
      this.src = this.images[this.i];
    }, 1000);
  }

  stopImg() {
    clearInterval(this.interval);
  }
}


<span>------------</span>
<h1>Show Pics</h1>
<span>------------</span>
<br>
<br>
  <input id="pb" type="button" (click)="prevImg()" value="previous">
  <input id="nb" type="button" (click)="nextImg()" value="next">
  <input id="ssb" type="button" (click)="slideImg()" value="Slide Show">
  <input id="sb" type="button" (click)="stopImg()" value="Stop">
  <br>
  <br>
  <img [src]="src" id="img" width="200" height="200">

// ITI/React/Lab2/lab/task2/react-slider/src/components/Slider.jsx
import React, { Component } from 'react'

export default class Slider extends Component {
  state = {
    images: [
      "Images/1.jpg",
      "Images/2.jpg",
      "Images/3.jpg",
      "Images/4.jpg",
      "Images/5.jpg",
      "Images/6.jpg",
    ],
    i: 0,
  };

  prevImg = () => {
    let i = this.state.i;
    if (i <= 0) i = this.state.images.length;
    i--;
    this.setState({ i });
  }

  nextImg = () => {
    let i = this.state.i;
    if (i >= this.state.images.length - 1) i = -1;
    i++;
    this.setState({ i });
  }

  render() {
    return (
      <>
        <span>------------------------------</span>
        <h1>&nbsp; Show Pics</h1>
        <span>------------</span>
        <br />
        <br />
        <input id="pb" type="button" onClick={this.prevImg} value="previous" />
        <input id="nb" type="button" onClick={this.nextImg} value="next" />
        <br />
        <br />
        <img
          src={this.state.images[this.state.i]}
          id="img"
          width="200"
          height="200"
          alt="slider"
        />
      </>
    );
  }
}
